[package]
name = "nw"
version = "0.1.0"
edition = "2021"

[dependencies]
cc = "1.0.97"
clap = { version = "4.5.4", features = ["derive"] }
human_bytes = "0.4.3"
libc = "0.2.154"
prettytable = "0.10.0"

[build-dependencies]
cc = "1.0.97"
